import Head from "next/head";
import Avatar from "../components/Avatar";
import { MicrophoneIcon, ViewGridIcon } from "@heroicons/react/solid";
import Image from "next/image";
import { SearchIcon } from "@heroicons/react/outline";
import Footer from "../components/Footer";
import {useRef} from "react"
import router, {useRouter} from "next/router"

export default function Home() {

  const searchInputRef = useRef(null);

const search=(e)=>{
  e.preventDefault();
  const term = searchInputRef.current.value;

  if (!term)return;

  router.push(`/search?term=${term}`)

}

  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://www.google.com/images/branding/googleg/1x/googleg_standard_color_128dp.png" />
      </Head>
      <header
        className="flex w-full p-5 justify-between 
      text-sm text-gray-700 "
      >
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>
        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Images</p>
          <ViewGridIcon className="h-10 w-10 p-2 rounded-full hover:bg-gray-200 cursor-pointer" />
          <Avatar url="https://png.pngtree.com/png-vector/20191101/ourmid/pngtree-cartoon-color-simple-male-avatar-png-image_1934459.jpg" />
        </div>
      </header>

      <form className="flex flex-col items-center flex-grow mt-44 w-4/5 ">
        <Image
          src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/552px-Google_2015_logo.svg.png"
          height={100}
          width={300}
        />
        <div
          className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg 
          max-w-md rounded-full border-gray-300 px-5 py-3 items-center sm:max-w-xl
          lg:max-w-2xl  border"
        >
          <SearchIcon className="h-5 mr-3 text-gray-500 " />
          <input ref={searchInputRef} type="text" placeholder="Search Google or type a url" className="flex-grow focus:outline-none  " />
          <MicrophoneIcon className="h-5" />
        </div>
        <div className="flex flex-col w-1/2 space-y-2 justify-center
         mt-8 sm:space-y-0 sm:flex-row sm:space-x-4 ">
          <button onClick={search} className="btn">
            Google Search
          </button>
          <button onClick={search} className="btn">
            I'm Feeling Lucky
          </button>
        </div>
      </form>
      <Footer/>
    </div>
  );
}
